CREATE TABLE users (
  user_id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  hashed_password TEXT NOT NULL,
  created_at TIMESTAMPZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE urls (
  url_id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  long_url TEXT NOT NULL,
  short_url VARCHAR(15) UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE analytics (
  analytics_id SERIAL PRIMARY KEY,
  short_url VARCHAR(15) NOT NULL REFERENCES urls(short_url) ON DELETE CASCADE,
  total_visits INT DEFAULT 0,
  last_visited TIMESTAMPTZ,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);